username: "hurtsec"
email: "hurtsec@gmail.com"
user: "{{ lookup('ansible.buildin.env', 'USER') }}"
home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
ssh_key_filename: "id_hurtsec_ed25519"
source_key: "./.ssh/{{ ssh_key_filename }}"
dest_key: "{{ home }}/.ssh/{{ ssh_key_filename }}"
config: "{{ lookup('ansible.buildin.env', 'XDG_CONFIG') }}"
personal: "{{ home }}/personal"
dev: "{{ personal }}/dev"
intel_brew_path: /usr/local/bin/brew
arm_brew_path: /opt/homebrew/bin/brew
