- name: Install and configure zsh
  hosts: localhost
  gather_facts: yes
  vars:
    user_home: "{{ ansible_env.HOME }}"
  tasks:
  - name: Check if oh-my-zsh is already installed
    stat:
      path: "{{ user_home }}/.oh-my-zsh"
    register: ohmyzsh
  - name: Install oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    args:
      creates: "{{ user_home }}/.oh-my-zsh"
    when: not ohmyzsh.stat.exists
    become: no
  - name: Check if zsh plugin autosuggestions exists
    stat:
      path: "{{ user_home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
    register: ohmyzsh_autosuggestions
  - name: Install zsh plugin autosuggestions
    ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    args:
      creates: "{{ user_home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
    when: not ohmyzsh_autosuggestions.stat.exists
