- name: Install GNU Stow
  homebrew:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow
- name: Clone .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:hurtsec/.dotfiles.git"
    dest: "{{ home }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Unstow .dotfiles
  command: stow -D {{ item }}
  args:
    chdir: "{{ home }}/.dotfiles"
  with_items:
  - bin
  - tmux
  - zsh
  tags:
  - install
  - dotfiles
  - stow
- name: Stow .dotfiles
  command: stow {{ item }} 
  args:
    chdir: "{{ home }}/.dotfiles"
  with_items:
  - bin
  - tmux
  - zsh
  tags:
    - install
    - dotfiles
    - stow
