- name: Install GNU Stow
  homebrew:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow
- name: Clone .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:hurtsec/.dotfiles.git"
    dest: "{{ home }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Unstow .dotfiles
  command: stow -D {{ item }}
  args:
    chdir: "{{ home }}/.dotfiles"
  with_items:
  - bin
  - tmux
  - zsh
  - skhd
  - yabai
  tags:
  - install
  - dotfiles
  - stow
- name: Unstow VS Code Settings Files
  command: stow -D -t ~/Library/Application\ Support/Code/User/ {{ item }}
  args:
    chdir: "{{ home }}/.dotfiles"
  with_items:
  - code
- name: Stow .dotfiles
  command: stow {{ item }} 
  args:
    chdir: "{{ home }}/.dotfiles"
  with_items:
  - bin
  - tmux
  - zsh
  - skhd
  - yabai
  tags:
    - install
    - dotfiles
    - stow
- name: Stow VS Code Settings Files
  command: stow -t ~/Library/Application\ Support/Code/User {{ item }}
  args:
    chdir: "{{ home }}/.dotfiles"
  with_items:
  - code
  tags:
  - install
  - dotfiles
  - stow